### ISSUE TITLE
Latest RC fails to start on Debian

### ISSUE THREAD

**Issue by algernon** [sboesebeck/ErgodoxLayoutGenerator#1]
I'm trying to run the program on Debian stable (with OpenJDK 8 from backports), but after downloading the JAR, I get the same error whether I run via `java -jar` or `java -cp`:

```
Error: Could not find or load main class de.caluga.ergodox.Main
```

My JDK is this:

```
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```

Will try to compile from source, and see if that helps.

**Comment by algernon** [comment]
Building with Maven or IntelliJ IDEA results in the same error.

(I had to add `jfxrt` as a module dependency in IDEA, to be able to compile the project, FYI)

**Comment by algernon** [comment]
Managed to make it run from IDEA, by using the Application config... Not really sure what I did, mind you.

**Comment by sboesebeck** [comment]
Hi,

Cool to see somebody else is using my tool ;). 
I think the problems were related to the use of openjdk. There are some differences and I only tested it with sun / oracle jdk. And Only on a Mac. So I really hope it'll work for you...

If you run mvn install it should generate a jar file in target containing all kind etc. could you try that? It's called *_shaded.jar. 

Cheers,

Stephan

**Comment by algernon** [comment]
Yep, tried that, same thing. Compilation originally failed because it didn't find `javafx` stuff, which is - on Debian - in a separate package, and I had to add it to the dependencies. Once that was done, I had to figure out how to run it. Had no luck with Maven, but managed to launch it from IDEA.

Sadly, whatever settings I made in IDEA, are not reflected in git-tracked files, otherwise I'd be opening a pull request by now.

In any case, my immediate problem is solved, I can run the layout generator. I suppose the issue can be solved, as it may be an issue in my environment, and not in the software itself. If I find out how to run it without IDEA on Debian, I'll open a PR! :)

**Comment by sboesebeck** [comment]
I put the IDEA-Files into .gitignore as I did not want to interfere with your settings. Sorry, that it actually caused problems.

but starting it should be very easy: only run de.caluga.ergodox.Main

or: java -jar target/ErgodoxLayoutGenerator-1.0-SNAPSHOT-shaded.jar

should also work after running mvn install

hope that helped a bit!

Glad that everything works for you now!

Thanks!
