### ISSUE TITLE
Unsupported function call SHFT_T(KC_SPACE) might cause problems when saving

### ISSUE THREAD

**Issue by squarology** [sboesebeck/ErgodoxLayoutGenerator#5]
Hello @sboesebeck I created this key in my layout and when I open it, it shows me this warning. So far I have opened and closed the file and there hasn't been a problem. I haven't gotten the keyboard yet so I haven't tested the key to see if it works.

My question is, is this warning because of the quantum firmware source or does it have to do with ELG?

thank you

**Comment by sboesebeck** [comment]
Hi,

this is actually a bug in ELG.. I'll fix it and create a new release - 
give me a day or two... 😉

Cheers,

Stephan

**Comment by sboesebeck** [comment]
just created a new release fixing this issue.

**Comment by squarology** [comment]
nice!
