### ISSUE TITLE
Reference to unknown layer found 1 might …

### ISSUE THREAD

**Issue by htgoebel** [sboesebeck/ErgodoxLayoutGenerator#8]
When loading the "german" keymap from the [original QMK firmware](https://github.com/jackhumbert/qmk_firmware), I get these error messages:
"Reference to unknown layer found 1 might cause problems compiling it." and
"Reference to unknown layer found 2 might cause problems compiling it."

I do not understand these messages. Maybe they should read "…unknown layer '1' found, …"?

The keymap.c file contains these definitions at the top:

```
// Layer names
#define BASE 0 // default layer
#define SYMB 1 // symbol layer
#define MDIA 2 // media keys
```

and all three layers are displayed (by name) in the layout generator.

Using ergodoxgenerator-1.0.5.jar

**Comment by sboesebeck** [comment]
Hi,
The problem is not the definition but the usage. There is a call for some layer using the number and not the name - that is confusing ELG for now. 

I changed most of the layers to work with ELG but could not do it for all unfortunately 

Cheers

Stephan

Von meinem iPhone gesendet

**Comment by htgoebel** [comment]
Yes, I discovered `TG(1)` and `TG(2)` in the key definitions. after changing these into `TG(SYMB)` resp. `TG(MDIA)`, the error message is gone.
